# Generated by Django 5.1.7 on 2025-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0002_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_id',
            field=models.IntegerField(),
        ),
    ]
