# Generated by Django 5.1.7 on 2025-04-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0003_alter_resume_resume_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_id',
        ),
    ]
