# Generated by Django 5.1.7 on 2025-04-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0004_remove_resume_resume_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headhuntertoken',
            name='user_id',
        ),
        migrations.AddField(
            model_name='headhuntertoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headhuntertoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='hh_resume_id',
            field=models.IntegerField(null=True),
        ),
    ]
