# Generated by Django 5.1.7 on 2025-04-05 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0005_remove_headhuntertoken_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='headhuntertoken',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='headhuntertoken',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headhuntertoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
